DROP TABLE EVENT_MEMBERS;
CREATE TABLE EVENT_MEMBERS (
	EventID INT,
	MemberID INT,
	CONSTRAINT uniqueEventMember UNIQUE (EventID, MemberID),
	CONSTRAINT FK_EventMembers_MemberID FOREIGN KEY (MemberID) REFERENCES USER(UserID),
	CONSTRAINT FK_EventMembers_EventID FOREIGN KEY (EventID) REFERENCES EVENT(EventID)
);